### ISSUE TITLE
dependencies?

### ISSUE THREAD

**Issue by Reual4412** [Gericom/Rtc3DS#1]
been trying to compile the test app. But
Rtc3DS-master/arm7/source/main.cpp:5:10: fatal error: Rtc3DS_uc11.h: No such file or directory
    5 | #include "Rtc3DS_uc11.h
it seems the source code is missing something or has a decencies I'm not aware of.

**Comment by SonoSooS** [comment]
How are you invoking `make`? Sounds like you may be using the parallel `-m` option.

If you're not using `-m` then try `make checkarm11 checkarm9 checkarm7 all`.

**Comment by Reual4412** [comment]
[cmd log.txt](https://github.com/Gericom/Rtc3DS/files/4505676/cmd.log.txt)
I tried both "make checkarm11 checkarm9 checkarm7 all" and just normal "make"

**Comment by Reual4412** [comment]
I could be stupid, and just be screwing something up, I'm not super familiar with compiling (or issues that can come from the process) admittedly. I did try compiling stuff from devkit pro example folder (to make sure things do properly compile) and it works fine. Is there perhaps a specific version of devkit that I'm supposed to use? currently using the latest

**Comment by SonoSooS** [comment]
Ohh, I barely spotted it!

You named the folder `Rtc3DS-master` (because that's how it exists in the zip you download), but it has to be named just `Rtc3DS`

**Comment by Reual4412** [comment]
new issue
sorry about this
[cmd_log.txt](https://github.com/Gericom/Rtc3DS/files/4513946/cmd_log.txt)
it seems that it failed to link rtc3ds.elf due to a missing rule on the make target. Tried both commands

**Comment by SonoSooS** [comment]
That's weird. I have that folder, but it's empty. I guess you can just create it ¯\\_(ツ)_/¯

**Comment by Reual4412** [comment]
oh I am a idiot my lord. Sorry, I should of realized that was leading to a directory. I kinda turned off my brain with the last comment. Thank you for the help.

**Comment by SonoSooS** [comment]
Nah. It could've been that we forgot to upload an entire folder by accident; that's what these errors are for. In this rare case it's indeed just an empty folder 😄
